"""empty message

Revision ID: d0d348730f7a
Revises: 8dceddb2742b
Create Date: 2025-03-02 23:08:07.697226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d348730f7a'
down_revision: Union[str, None] = '8dceddb2742b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('created_by', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'created_by')
    # ### end Alembic commands ###
